### ISSUE TITLE
Hi! EFI for X250

### ISSUE THREAD

**Issue by PavlovMD** [qwerty12/X250-Hackintosh#3]
Hi!  I tried to install according to your instruction, but it turns out nothing. I cannot already install month OS on mine х250. Please, can you send me your folder EFI?

**Comment by qwerty12** [comment]
Hi,

If you really want it, then you can find it attached here. [EFI.zip](https://github.com/qwerty12/X250-Hackintosh/files/3397569/EFI.zip)

There is no proper SMBIOS definition so don't sign into iCloud, Messages etc. Please don't ask me for help with something already covered in the main guide.

I'll also point out that there's other EFI folders around if you can't get this to work. I don't claim that my setup for the X250 is the best around. See here, for example: https://www.hackintosh-forum.de/forum/thread/39260-mojave-auf-lenovo-x250-anpassung-nach-der-installation/?pageNo=7
