### ISSUE TITLE
DW1830

### ISSUE THREAD

**Issue by tonewheelz** [qwerty12/X250-Hackintosh#4]
Hi there

Thanks for your guide, it has worked flawlessly for me. 

I was wondering if you have some photos on how they have the antennas connected on the thinkpad? 
 
I’ve installed this on an X250, leaving J2 empty (also tried connecting the orange WWAN antenna).
 
I’m trying to get it working well in Windows before I try getting it up and running in macOS.
 
Here are my observations so far:
 
 
1. Downloading the drivers from Dell and trying to install them via the executable returns an error with no matching hardware ID found.
 
2. Device manager shows an unknown hardware labeled simply as “Network Controller”
 
3. Installing the driver manually via Device Manager cautions that the device may not be compatible, but installs successfully when I tell it to continue and install anyway.
 
4. After drivers are installed, only my 2ghz network is found, and when trying to connect it simply returns an error “cannot connect to network”.
 
 
Hoping I didn’t get a bum WiFi card. Any help would be greatly appreciated.

Thanks again

**Comment by qwerty12** [comment]
Hi,

I'm sorry, I don't have any photos. From memory, I currently have the wires plugged in oddly: the right-most Wi-Fi antenna is shoved all the way into J0, the left-most Wi-Fi antenna is in J1, and a WWAN antenna lies in J2. I did also have it working with just plugging in the nearest cables to each port. 

In the Device Manager, find your card under network adapters (or other devices), bring up its properties, select the details tab and see what its actual hardware ID is. My DW1830 is reported as `PCI\VEN_14E4&DEV_43BA`.  

I'm using [these](https://www.dell.com/support/home/uk/en/ukbsdt1/drivers/driversdetails?driverid=58ftm) drivers on Windows *10* (I'm 95% sure they don't support earlier versions of Windows).  I don't really have any suggestions, sorry.
